using System;
namespace Cafeteria_Card_Management
{
//     •	UserID (Auto Incremented – SF1001)
// •	WorkStationNumber
// Methods:
// •	WalletRecharge

    public class UserDetails:PersonalDetails,IBalance
    {
        private static int s_userID=1000;
        /// <summary>
        /// Each user has an own identity and it is autogenerated
        /// </summary>
        /// <value></value>
        public string UserID { get; }
        /// <summary>
        /// Each object have an workstation number
        /// </summary>
        /// <value></value>
        public string WorkStationNumber { get; set; }
        /// <summary>
        /// It shows the wallet balance of the user
        /// </summary>
        /// <value></value>
        public double WalletBalance{get;set;}
        /// <summary>
        /// This is a method to recharge a wallet
        /// </summary>
        /// <param name="amount"></param>
        public void WalletRecharge(double amount)
        {
            WalletBalance+=amount;
        }
        /// <summary>
        /// It belong to the class<see cref="UserDetails"/>
        /// </summary>
        /// <param name="name">It express user name</param>
        /// <param name="fatherName">It is a string and it holds the father name of the object</param>
        /// <param name="mobile">It holds the mobile number of current object</param>
        /// <param name="mail">It holds the mailID of current object</param>
        /// <param name="gender">It holds the gender of current object</param>
        /// <param name="workStationNumber">Each object have an workstation number</param>
        /// <param name="WalletBalance">It shows the wallet balance of the user</param>
        /// <returns></returns>
        public UserDetails(string name,string fatherName,long mobile,string mail,Gender gender,int workStationNumber,double WalletBalance):base(name,fatherName,gender,mobile,mail)
        {
            s_userID++;
            UserID="SF"+s_userID;
            WorkStationNumber="WS"+workStationNumber;
            this.WalletBalance=WalletBalance;
        }
        /// <summary>
        /// It belong to the class<see cref="UserDetails"/>
        /// </summary>
        /// <param name="name">It express user name</param>
        /// <param name="fatherName">It is a string and it holds the father name of the object</param>
        /// <param name="mobile">It holds the mobile number of current object</param>
        /// <param name="mail">It holds the mailID of current object</param>
        /// <param name="gender">It holds the gender of current object</param>
        /// <param name="workStationNumber">Each object have an workstation number</param>
        /// <returns></returns>
        public UserDetails(string name,string fatherName,long mobile,string mail,Gender gender,int workStationNumber):base(name,fatherName,gender,mobile,mail)
        {
            s_userID++;
            UserID="SF"+s_userID;
            WorkStationNumber="WS"+workStationNumber;
        }
        /// <summary>
        /// It displays all the properties of Userdetails class of current object
        /// </summary>
        public void ShowUserDetails()
        {
            System.Console.WriteLine("|{0,-10}|{1,-18}|{2,-16}|{3,-14}|{4,-16}|{5,-12}|{6,-19}|{7,-15}|",UserID,Name,FatherName,Mobile,MailID,Gender,WorkStationNumber,WalletBalance);
        }
        
    }
}